spring:
  mvc:
    cors:
      mapping: /**
      allowed-origins: "*"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: x-requested-with, Content-Type
      allow-credentials: true
      max-age: 3600
      expose-headers: content-disposition
      exposed-headers: content-disposition
      Content-Type: application/json;charset=UTF-8, text/javascript, */*

  main:
    lazy-initialization: false
  datasource:
    url: jdbc:mysql://localhost:3306/ruanxie
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
      active: dev
  logging:
    level:
      springfox: error
      root: info
      com.management.deviceManage.mapper.*: debug

server:
  port: 8080
  servlet:
    session:
      timeout: PT24H
